name: rodin_essential_ui
description: Rodin Essential zero-DEX Flutter AOT interface.
publish_to: "none"
version: 1.18.3+11803

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
